LinJas/Areas/AdminLinja/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LinJas.Areas.AdminLinja.Common;
using System.IO;
using LinJas.Areas.AdminLinja.Models;
using LinJas.Areas.AdminLinja.Models.AuthModel;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

namespace LinJas.Areas.AdminLinja.Controllers
{
    public class TagController : Controller
    {
        private readonly ManagerModel _db;
        public TagController()
        {
            _db = new ManagerModel();
        }
        // clear bộ nhớ
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            _db.Dispose();
        }
        // GET: AdminLinja/Tag
        public ActionResult Index()
        {
            return View();
        }       
       
        public ActionResult GetDetail(int id)
        {
            var listItems = _db.Database.SqlQuery<TagModel>(TVConstants.StoredProcedure.AdminTag.TagBlogSelectById, id).FirstOrDefault();
            return Json(listItems, JsonRequestBehavior.AllowGet);
        }   
        public ActionResult InsertTag(string name, int? sortOrder, int? loai)
        {
            var mediaData = new byte[] { 0x20 };
            var moTa = "";
            var result = 0;
            result =
                _db.Database.ExecuteSqlCommand(
                TVConstants.StoredProcedure.AdminTag.TagBlogInsert, name, sortOrder, loai, moTa, mediaData);

            var text = "Thêm thành công";
            if (result == 0) text = "Thêm Thất bại";
            return Json(new { Num = result, Message = text }, JsonRequestBehavior.AllowGet);

        }
        public ActionResult UpdateTag(int? id, string name, int? sortOrder, int? loai)
        {
            var mediaData = new byte[] { 0x20 };
            var moTa = "";
            var result = 0;
            result =
                _db.Database.ExecuteSqlCommand(
               TVConstants.StoredProcedure.AdminTag.TagBlogUpdate, id, name, sortOrder, loai, moTa, mediaData);
            var text = "Sửa thành công";
            if (result == 0) text = "Sửa Thất bại";
            return Json(new { Num = result, Message = text }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult DeleteTag(int? id)
        {
            var result = _db.Database.ExecuteSqlCommand(TVConstants.StoredProcedure.AdminTag.TagBlogDelete, id);
            var text = "Đã xóa thành công";
            if (result == -1)
                text = "Không được xóa đối tác này";
            return Json(new { Num = result, Message = text }, JsonRequestBehavior.AllowGet);
        }
    }
}

LinJas/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LinJas.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        public ActionResult Index()
        {
            return View();
        }
    }
}

LinJas/Areas/AdminLinja/Views/Shared/_Arlert.cshtml


<div>
    @(Html.Kendo().Window()
          .Name("windowConfirm")
          .Title("Thông báo")
          .Visible(false)
          .Draggable()
          .Resizable()
          .Modal(true)
          .Width(420)
          .Height(120)
          .Actions(actions => actions.Close())
          .AutoFocus(true)
          .Content(@<text>
            <h4>
                Bạn có chắc chắn không?
            </h4>
            <div class="checkconfirm">
                <button type="button" id="confirmYes" class="btn btn-primary">Yes</button>
                <button type="button" id="confirmNo" class="btn btn-default">No</button>
            </div>
        </text>)
    )

</div>

LinJas/Areas/AdminLinja/Views/Shared/_Layouts.cshtml
<!DOCTYPE html>
<html>
<head>
    @RenderSection("head", required: false)
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @*<link rel="icon" href="~/Images/icon/xingfa-icon.png" sizes="32x32" />
        <link rel="icon" href="~/Images/icon/xingfa-icon.png" sizes="192x192" />
        <link rel="apple-touch-icon-precomposed" href="~/Images/icon/xingfa-icon.png" />
        <meta name="msapplication-TileImage" content="~/Images/icon/xingfa-icon.png" />*@
    <link rel="icon" href="~/favicon.ico" sizes="32x32" />

    <link href="~/Areas/AdminLinja/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Areas/AdminLinja/Content/Site.css" rel="stylesheet" />
    <link href="~/Areas/AdminLinja/Content/ninja-common.css" rel="stylesheet" />

    <link href="~/Areas/AdminLinja/Content/kendo/kendo.common.min.css" rel="stylesheet" />
    <link href="~/Areas/AdminLinja/Content/kendo/kendo.default.min.css" rel="stylesheet" />
    <link href="~/Areas/AdminLinja/Content/kendo/kendo.dataviz.default.min.css" rel="stylesheet" />
    <link href="~/Areas/AdminLinja/Content/kendo/kendo.dataviz.min.css" rel="stylesheet" />


    <script src="~/Areas/AdminLinja/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Areas/AdminLinja/Scripts/kendo/kendo.all.min.js"></script>
    <script src="~/Areas/AdminLinja/Scripts/kendo/kendo.aspnetmvc.min.js"></script>
    <script src="~/Areas/AdminLinja/Scripts/jquery.validate.js"></script>
    <script src="~/Areas/AdminLinja/Scripts/bootstrap.js"></script>
    <script src="~/Areas/AdminLinja/Scripts/respond.js"></script>
</head>
<body class="content">
    <!--Menu-->
    @Html.Partial("_Menu")
    <div>
        @RenderBody()
    </div>
    <!--Thông báo-->
    <div>
        @(Html.Kendo().Window()
        .Name("windowPopup")
        .Title("Thông báo")
         .Visible(false)
         .Draggable()
        //.Resizable()
        .Modal(true)
        .Width(350)
        //.Actions()
        .AutoFocus(true)
        .Content(@<text>
            <span id="tlAllPopup">
                Bạn có chắc chắn không?
            </span>
            <div id="puBottom">
                <center>
                    <button type="button" id="BTN1" class="btn btn-primary">Yes</button> &nbsp;&nbsp;&nbsp;&nbsp;
                    <button type="button" id="BTN2" class="btn btn-default">No </button>
                </center>
            </div>
        </text>)
        .HtmlAttributes(new { @class = "no-buttons" })
        )

    </div>

    <script type="text/javascript">

        function showAlertView(message, titleBTN1, titleBTN2, callBack) {
            document.getElementById("tlAllPopup").innerHTML = message;

            $("#BTN1").hide();
            $("#BTN2").hide();

            if ((titleBTN1 != null) && (titleBTN1.length > 0)) {
                $("#BTN1").show();
                document.getElementById("BTN1").innerHTML = titleBTN1;

            }
            if ((titleBTN2 != null) && (titleBTN2.length > 0)) {
                $("#BTN2").show();
                document.getElementById("BTN2").innerHTML = titleBTN2;
            }


            $("#windowPopup").data("kendoWindow").center().open();
            $("#BTN1").unbind();
            $('#BTN1').click(function () {
                $("#windowPopup").data("kendoWindow").close();
                if (callBack) {
                    callBack(1);
                }

            });

            $('#BTN2').click(function () {
                $("#windowPopup").data("kendoWindow").close();
                if (callBack) {
                    callBack(2);
                }
            });

        }

        // --- Đổi màu cell khi di chuột đến cell

        function moveMouseInCell(Id, gridName) {
            if ((gridName == null) || (gridName === undefined)) {

                grid = "grid";
            }
            gridName = '#' + gridName;

            var gview = $(gridName).data("kendoGrid");
            var data = gview.dataSource.data();
            for (var i = 0; i < data.length; i++) {
                var item1 = data[i];
                if (item1.Id == Id) {
                    $('tr[data-uid="' + item1.uid + '"] ').css("background-color", "orange");
                    $('tr[data-uid="' + item1.uid + '"] ').css("color", "black");

                    break;
                }

            }
        }

        function onMouseOutMove(Id, gridName) {

            if (!gridName) {

                grid = "grid";
            }

            gridName = '#' + gridName;

            var gview = $(gridName).data("kendoGrid");
            var data = gview.dataSource.data();
            for (var i = 0; i < data.length; i++) {
                var item1 = data[i];
                if (item1.Id == Id) {

                    if ((i % 2) == 0) {
                        $('tr[data-uid="' + item1.uid + '"] ').css("background-color", "transparent");
                    }
                    else {

                        $('tr[data-uid="' + item1.uid + '"] ').css("background-color", "#f5f5f5");
                    }

                    changerTextCellColor(gridName, item1);

                    break;
                }

            }
        }


        function changerTextCellColor(gridName, item1) {


            if (gridName == "#grid-khachhang") {

                var trangThaiId = item1["TrangThaiId"];
                var trangThaiHang = item1["TrangThaiHang"];

                if (((trangThaiId == 2) || (trangThaiId == 3) || (trangThaiId == 11) || (trangThaiId == 12) || (trangThaiId == 13) || (trangThaiHang == 1) || (trangThaiHang == 5)) && (trangThaiHang != 6)) {

                    $('tr[data-uid="' + item1.uid + '"] ').css("color", "red");

                } else if (((trangThaiId == 1) || (trangThaiId == 4) || (trangThaiId == 5) || (trangThaiHang == 2) || (trangThaiHang == 3) || (trangThaiHang == 4)) && (trangThaiHang != 6)) {

                    //$('tr[data-uid="' + item1.uid + '"] ').css("color", "#f5f5f5");


                } else {

                    $('tr[data-uid="' + item1.uid + '"] ').css("color", "#30c60f");

                }
                //td: eq(13)


            } else if (gridName == "#grid-datchotruoc") {

                //--- Check giành cho cuộc gọi đặt trước.
                var gviewTruoc = $("#grid-datchotruoc").data("kendoGrid");
                var dataTruoc = gviewTruoc.dataSource.data();

                for (var i = 0; i < dataTruoc.length; i++) {
                    var item = dataTruoc[i];
                    var trangThaiHang = item["TrangThaiHang"];

                    if ((trangThaiHang == 1) || (trangThaiHang == 5)) {

                        $('tr[data-uid="' + item.uid + '"] ').css("color", "red");

                    } else if (trangThaiHang == 6) {

                        $('tr[data-uid="' + item.uid + '"] ').css("color", "#30c60f");
                    }
                }
            }
        }

        //_Hiển thị thông báo lỗi ngay trên popup.
        function showErrorInPopup(message) {
            $("#ErrorMessage").show();
            document.getElementById("ErrorMessage").innerHTML = message;
        }

    </script>

</body>
</html>

LinJas/Areas/AdminLinja/Views/Shared/_Menu.cshtml
<div id="headmenu">
    <div id="megaStore">
        <ul id="menu">
            <li><a href="@Url.Action("Index","Roles",new { Area="AdminLinja" })">Phân Quyền</a></li>
            <li>
             Danh mục
                <ul>
                    <li><a href="@Url.Action("Index","QuanHuyen",new { Area="AdminLinja" })">Quận Huyện</a></li>                    
                    <li><a href="@Url.Action("Index","Tag",new { Area="AdminLinja" })">Thẻ Tag</a></li>
                    <li>Beds</li>
                </ul>
            </li>            
            <li>
               Sản phẩm
                <ul>
                    <li><a href="@Url.Action("Index","DanhMuc",new { Area="AdminLinja" })">Chuyên mục</a></li>
                    <li><a href="@Url.Action("Index","SanPham",new { Area="AdminLinja" })">Sản phẩm</a></li>
                </ul>
            </li>
            <li><a href="@Url.Action("Index","Blog",new { Area="AdminLinja" })">Blog</a></li>
            <li>
                Events
            </li>
            <li disabled="disabled">
                News
                <ul>
                    <li>
                        Furniture
                        <ul>
                            <li>Tables & Chairs</li>
                            <li>Sofas</li>
                            <li>Occasional Furniture</li>
                            <li>Children's Furniture</li>
                            <li>Beds</li>
                        </ul>
                    </li>
                    <li>
                        Decor
                        <ul>
                            <li>Bed Linen</li>
                            <li>Throws</li>
                            <li>Curtains & Blinds</li>
                            <li>Rugs</li>
                            <li>Carpets</li>
                        </ul>
                    </li>
                    <li>
                        Storage
                        <ul>
                            <li>Wall Shelving</li>
                            <li>Kids Storage</li>
                            <li>Baskets</li>
                            <li>Multimedia Storage</li>
                            <li>Floor Shelving</li>
                            <li>Toilet Roll Holders</li>
                            <li>Storage Jars</li>
                            <li>Drawers</li>
                            <li>Boxes</li>
                        </ul>

                    </li>
                    <li>
                        Lights
                        <ul>
                            <li>Ceiling</li>
                            <li>Table</li>
                            <li>Floor</li>
                            <li>Shades</li>
                            <li>Wall Lights</li>
                            <li>Spotlights</li>
                            <li>Push Light</li>
                            <li>String Lights</li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>

    <script>
            $(document).ready(function() {
                $("#menu").kendoMenu();
            });
    </script>
</div>
